AutoShop_Web/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoShop_Shared.Models;
using AutoShop_Shared.Services;

namespace AutoShop_Web.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        public ArticleController(IArticleService a)
        {
            _articleService = a;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

AutoShop_Web/Controllers/BadgeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoShop_Shared.Models;
using AutoShop_Shared.Services;
using Microsoft.AspNetCore.Mvc;

namespace AutoShop_Web.Controllers
{
    public class BadgeController : Controller
    {
        List<Badge> badges = new List<Badge>();

        private readonly IBadgeService _badgeService;

        public BadgeController(IBadgeService b)
        {
            _badgeService = b;
        }

        public IActionResult Index()
        {
            List<Badge> badges = _badgeService.GetBadges();
            //Badge badge = new Badge
            //{
            //    Title = "Over archivement",
            //    Label = "Overload these lasts times : 10x more products bought than usual !!!",
            //    Picture = "OverArchivement.png"
            //};
            //badges.Add(badge);
            //badge = new Badge
            //{
            //    Title = "Gost",
            //    Label = "Long time not seen, you moron è_é",
            //    Picture = "gost.png"
            //};
            //badges.Add(badge);
            //badge = new Badge
            //{
            //    Title = "Hardware Buyer",
            //    Label = "What are you gonna do with all these mics ?",
            //    Picture = "hardwareBuyer.png"
            //};
            //badges.Add(badge);


            return View(badges);
        }
    }
}

AutoShop_Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AutoShop_Shared.Models;

namespace AutoShop_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AutoShop_Web/Controllers/SuggestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoShop_Shared.Models;

namespace AutoShop_Web.Controllers
{
    public class SuggestionController : Controller
    {
        public ActionResult Index()
        {
            Suggestion s = new Suggestion();
            s.Title = "Suggestion 1";
            Suggestion s2 = new Suggestion();
            s2.Title = "Suggestion 2";
            Suggestion s3 = new Suggestion();
            s3.Title = "Suggestion 3";

            List<Suggestion> liste = new List<Suggestion>();
            liste.Add(s);
            liste.Add(s2);
            liste.Add(s3);
            return View(liste);
        }
    }
}

AutoShop_Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoShop_Shared.Models;
using AutoShop_Shared.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AutoShop_Web.Controllers
{
    public class UserController : Controller
    {

        List<Badge> badges = new List<Badge>();
        List<User> users = new List<User>();

        private readonly IUserService _userService;
        private readonly IBadgeService _badgeService;

        public UserController(IUserService u, IBadgeService b)
        {
            _userService = u;
            _badgeService = b;
        }

        public IActionResult Index()
        {
           
            List<User> users = _userService.GetUsers(25);
            //Chercher le contenu de l'objet badge de l'atribut ActiveBadge
            foreach (User user in users)
            {
                if (user.ActiveBadge != null)
                {
                    Badge bb = _badgeService.GetBadge(user.ActiveBadge.Title.ToString()).First();
                    user.ActiveBadge = bb;
                }
            }
            ViewData["title"] = "Titre de la page";
            return View(users);
        }
        public IActionResult Details(string id)
        {
            User user = _userService.GetUser(id);
            return View("Details",user);
        }
        public IActionResult Edit(string id)
        {
            User user = _userService.GetUser(id);
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, IFormCollection collection)
        {
            User user = _userService.GetUser(id);
            return View(user);
        }
    }
}

AutoShop_Web/Views/Badge/Index.cshtml
@model List<Badge>;
@{
    ViewData["Title"] = "Index";
}

<h1>Badges</h1>
<br />
<div class="row">
    <ul class="list-group">
        @foreach (Badge item in Model)
        {
            <li>

                <h4>@item.Title</h4>
                <div>
                    <img class="img-fluid" height="128" width="128" src="~/picture/badge/@item.Picture" />
                    @item.Label
                </div>
            </li>
        }
    </ul>
</div>

AutoShop_Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AutoShop_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoShop_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutoShop_Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Badge" asp-action="Index">Badge</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Article</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AutoShop_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AutoShop_Web/Views/Suggestion/Index.cshtml
@model List<AutoShop_Shared.Models.Suggestion>;
@{
    ViewData["Title"] = "Index";
}

<h1>Suggestion</h1>
@foreach (Suggestion s in Model)
{
    <h2>@s.Title</h2>
}

AutoShop_Web/Views/User/Details.cshtml
@model AutoShop_Shared.Models.User

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Level)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Level)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Experience)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Experience)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

AutoShop_Web/Views/User/Edit.cshtml
@model AutoShop_Shared.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" class="form-control" hidden />
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email*</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Level" class="control-label"></label>
                <input asp-for="Level" class="form-control" />
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Experience" class="control-label"></label>
                <input asp-for="Experience" class="form-control" />
                <span asp-validation-for="Experience" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AutoShop_Web/Views/User/Index.cshtml
@model List<User>
@{
    ViewData["Title"] = "Index";
    int maxLevel = 50;
    uint maxExeperience = 4000000;
}

<h1>Utilisateurs</h1>
<br />
<div class="row">
    <div class="card-deck">
        @foreach (User item in Model)
        {
            int level = (int)(item.Level * 100 / maxLevel);
            int experience = (int)(item.Experience * 100 / maxExeperience);


        <div class="card bg-dark text-center text-light">
            <div class="card-title ">@item.Email</div>
            <div class="card-body">
                <div class="card-img"><img class="img-fluid" src="~/picture/user/@item.Picture" /></div>
                <div class="card-title">
                    @item.LastName
                    <br />@item.FirstName
                    <br />
                    <br />
                    LVL @item.Level

                    <div class="progress">
                        <div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width:@level%" aria-valuenow="@item.Level" aria-valuemin="0" aria-valuemax="@maxLevel.ToString("N0")"></div>
                        <div class="progress-bar progress-bar-striped bg-dark" role="progressbar" style="width:100%"></div>
                    </div>
                    <br />
                    <br />
                    XP @item.Experience
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width:@experience%" aria-valuenow="@item.Experience" aria-valuemin="0" aria-valuemax="@maxExeperience.ToString("N0")"></div>
                        <div class="progress-bar progress-bar-striped bg-dark" role="progressbar" style="width:100%"></div>
                    </div>
                    <div>
                        @if(item.ActiveBadge != null)
                    {
                        <img class="img-fluid" height="128" width="128" src="~/picture/badge/@item.ActiveBadge.Picture" />
                        @item.ActiveBadge.Title <br />
                        @item.ActiveBadge.Label
                    }
                    </div>
                    </div>


                <div class="card-footer float-right">
                    <button class="btn btn-primary " typeof="button">Upload</button>
                    @Html.ActionLink("Detail", "Details", new { id = item.Id },new{@class = "btn btn-danger float-right mr-2"})
                </div>
            </div>
        </div>
        }
    </div>
</div>